package com.redflag.pineapple.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF636100)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEEE913)
val md_theme_light_onPrimaryContainer = Color(0xFF1D1D00)
val md_theme_light_secondary = Color(0xFF206D00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFA2F87E)
val md_theme_light_onSecondaryContainer = Color(0xFF052100)
val md_theme_light_tertiary = Color(0xFF316B00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF9CFA5D)
val md_theme_light_onTertiaryContainer = Color(0xFF0A2100)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF271900)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF271900)
val md_theme_light_surfaceVariant = Color(0xFFE6E3D1)
val md_theme_light_onSurfaceVariant = Color(0xFF48473A)
val md_theme_light_outline = Color(0xFF797769)
val md_theme_light_inverseOnSurface = Color(0xFFFFEED9)
val md_theme_light_inverseSurface = Color(0xFF422C00)
val md_theme_light_inversePrimary = Color(0xFFD1CC00)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF636100)

val md_theme_dark_primary = Color(0xFFD1CC00)
val md_theme_dark_onPrimary = Color(0xFF333200)
val md_theme_dark_primaryContainer = Color(0xFF4B4900)
val md_theme_dark_onPrimaryContainer = Color(0xFFEEE913)
val md_theme_dark_secondary = Color(0xFF87DB65)
val md_theme_dark_onSecondary = Color(0xFF0D3900)
val md_theme_dark_secondaryContainer = Color(0xFF165200)
val md_theme_dark_onSecondaryContainer = Color(0xFFA2F87E)
val md_theme_dark_tertiary = Color(0xFF81DD43)
val md_theme_dark_onTertiary = Color(0xFF163800)
val md_theme_dark_tertiaryContainer = Color(0xFF235100)
val md_theme_dark_onTertiaryContainer = Color(0xFF9CFA5D)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF271900)
val md_theme_dark_onBackground = Color(0xFFFFDEAB)
val md_theme_dark_surface = Color(0xFF271900)
val md_theme_dark_onSurface = Color(0xFFFFDEAB)
val md_theme_dark_surfaceVariant = Color(0xFF48473A)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC7B6)
val md_theme_dark_outline = Color(0xFF939181)
val md_theme_dark_inverseOnSurface = Color(0xFF271900)
val md_theme_dark_inverseSurface = Color(0xFFFFDEAB)
val md_theme_dark_inversePrimary = Color(0xFF636100)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD1CC00)


val seed = Color(0xFFEAE509)